name: player-ci
on:
  pull_request:
  push:
    branches: [main]
jobs:
  quality-and-native-build:
    runs-on: windows-2025
    defaults:
      run:
        working-directory: cloudgta-player
    env:
      CLOUDGTA_PLATFORM_REVISION: 1ae084d6fe3c9e904b9128965ba645fa96d5565c
    steps:
      - uses: actions/checkout@v4
        with:
          path: cloudgta-player
      - uses: actions/checkout@v4
        with:
          repository: ${{ github.repository_owner }}/cloudgta-docs
          ref: 6464a9b92dfae404458e259046fe72b60b4d72b2
          path: docs
          ssh-key: ${{ secrets.DOCS_DEPLOY_KEY }}
      - shell: pwsh
        run: ./scripts/bootstrap.ps1
